[package]
name = "sealed_box"
version = "0.1.2"
edition = "2021"
authors = ["Antonio Estévez <aestevez@kore-ledger.net>"]

[dependencies]
anyhow = "1.0"
blake2 = "0.10"
crypto_box = { version = "0.9.1", features = ["chacha20"] }
generic-array = "1.0"
rand = "0.8"
